name: sqfentity_gen
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfnEntity Model Generator. SQLite ORM for Flutter lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework.

version: 2.5.0
environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  build: 4.0.11
  source_gen: 4.2.4
  meta: 1.18.3
  analyzer: 13.3.0
  intl: 0.20.3
